In [2]:
l1 = [2324,256,127,-6523]

In [4]:
l1

[2324, 256, 127, -6523]

In [6]:
import numpy as np

In [7]:
a = np.array(l1)

In [8]:
a

array([ 2324,   256,   127, -6523])

In [9]:
b = np.array([12,455,63.3, True, 'abc'])

In [10]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [11]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U32')

In [12]:
l1.pop

<function list.pop(index=-1, /)>

In [13]:
l1

[2324, 256, 127, -6523]

In [14]:
l1.pop()

-6523

In [15]:
l1

[2324, 256, 127]

In [16]:
a.mean()

-954.0

In [17]:
c = np.array([12,455,63.3, True])

In [18]:
print(c)

[ 12.  455.   63.3   1. ]


In [20]:
d = np.array([12,455,63.3, False])

In [22]:
print(d)

[ 12.  455.   63.3   0. ]


In [26]:
l1[:]

[2324, 256, 127]

In [27]:
#---------

In [28]:
a

array([ 2324,   256,   127, -6523])

In [30]:
a[2:4]

array([  127, -6523])

In [31]:
b = a[2:4]

In [32]:
b

array([  127, -6523])

In [33]:
b[0]

127

In [35]:
b[:] = 111

In [37]:
b

array([111, 111])

In [38]:
a

array([2324,  256,  111,  111])

In [39]:
c = a.copy()

In [40]:
c

array([2324,  256,  111,  111])

In [41]:
c[0] = 0

In [42]:
c

array([  0, 256, 111, 111])

In [43]:
a

array([2324,  256,  111,  111])

In [44]:
c[4] = 56

IndexError: index 4 is out of bounds for axis 0 with size 4

In [45]:
c.put(56)

TypeError: put() missing required argument 'values' (pos 2)

In [46]:
c.put(4,56)

IndexError: index 4 is out of bounds for axis 0 with size 4

In [47]:
a = [1,2,3]

In [48]:
b = [4,5,6]

In [49]:
ab = []

In [50]:
for i in range(0,len(a)):
    ab.append(a[i]+b[i])

In [51]:
ab

[5, 7, 9]

In [52]:
doubled_a = [i*2 for i in a]

In [54]:
doubled_a

[2, 4, 6]